1107

diff --git a/tools/provision b/tools/provision
--- a/tools/provision
+++ b/tools/provision
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# Use this script to provision dependencies for your Zulip installation.
+# Use this script to provision dependencies for your Aloha installation.
 # This script is idempotent, so it can be restarted at any time, and it
 # will usually run fairly quickly when your dependencies are up to date.
 
@@ -20,7 +20,7 @@ fi
 os="$(. /etc/os-release && echo "$ID $VERSION_ID")"
 case "$os" in
     'ubuntu 14.04' | 'ubuntu 16.04' | 'ubuntu 18.04' | 'debian 10')
-        echo "Error: $os is no longer a supported platform for Zulip." >&2
+        echo "Error: $os is no longer a supported platform for Aloha." >&2
         if [ -e /home/vagrant ]; then
             # shellcheck disable=SC2016
             echo 'To upgrade, run `vagrant destroy`, and then recreate the Vagrant guest.' >&2
@@ -33,7 +33,7 @@ esac
 python_version="$(python3 --version)"
 case "$python_version" in
     Python\ 3.[0-7].*)
-        echo 'Error: Zulip requires an OS with Python 3.8 or later.' >&2
+        echo 'Error: Aloha requires an OS with Python 3.8 or later.' >&2
         exit 1
         ;;
 esac
@@ -71,8 +71,8 @@ if [ "$failed" -ne 0 ]; then
     exit "$failed"
 elif [ "$VIRTUAL_ENV" != "/srv/zulip-py3-venv" ] && [ -z "${SKIP_VENV_SHELL_WARNING}" ]; then
     echo -e "$WARNING"
-    echo "WARNING: This shell does not have the Zulip Python 3 virtualenv activated."
-    echo "Zulip commands will fail until you activate the virtualenv."
+    echo "WARNING: This shell does not have the Aloha Python 3 virtualenv activated."
+    echo "Aloha commands will fail until you activate the virtualenv."
     echo
     echo "To update the shell, run:"
     echo "    source /srv/zulip-py3-venv/bin/activate"
